FROM node:14 as builder
WORKDIR /usr/src/app
COPY ./client ./
RUN npm install
RUN npm run build

FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /usr/src/app/build .
COPY --from=builder /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]