AWSTemplateFormatVersion: '2010-09-09'
Description: An internal service discovery namespace
Parameters:
  EnvironmentName:
    Type: String
    Default: yossi-ecs
    Description: The name of the environment to add this service discovery namespace to
  Domain:
    Type: String
    Default: service.production
    Description: The name of the namespace. Services are prepended, for example user.service.production
Resources:
  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Ref Domain
      Vpc:
        Fn::ImportValue: !Sub ${EnvironmentName}:VpcId
Outputs:
  PrivateServiceDiscoveryNamespace:
    Description: The ID of the private service discovery namespace
    Value: !Ref ServiceDiscoveryNamespace
    Export:
      Name: !Sub ${EnvironmentName}:PrivateServiceDiscoveryNamespace