name: Check notification

on:
  push: {}
  release: {}

jobs:
  failing:
    name: test failur
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Try to fail
      run: exit 1
  if_failure:
    name: Only if failure
    runs-on: ubuntu-latest
    steps:
      - name: Try to fail
        run: exit 1
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "No ${variables} avaliable in here"
            }
  success:
    name: One with everything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL}}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
