name: Check notification

on:
  push: {}
  release: {}

jobs:
  failing:
    name: test failure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Try to fail
      run: exit 1
  if_failure:
    name: Only if failure
    runs-on: ubuntu-latest
    if: always()
    needs:
      - failing
    steps:
      - name: Overwrite status
        id: overwrites
        env:
          steps: ${{ toJson(steps) }}
          needs: ${{ toJson(needs) }}
      - name: Overwrite status env
        id: overwrites
        env:
          steps: ${{ toJson(env.steps) }}
          needs: ${{ toJson(env.needs) }}
      - id: Notify_failure
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          needs: ${{ env.needs }}
          job: ${{ toJson(env.needs.job) }}
          steps: ${{ env.needs.steps }}
