# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: template
        uses: traversals-analytics-and-intelligence/file-reader-action@master
        with:
          file: "abc.txt"

      - name: File contents
        run: echo "${{ steps.template.outputs.content }}"

      - name: criteria for passing
        run: if [ ${{ steps.template.outputs.content }} == "pass" ]; then exit 0; else exit 1; fi
  notify:
    needs:
      - build
    name: sending message
    runs-on: ubuntu-latest
    if: always()
    steps:
      - id: Notify_failure
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          job: '{ "status": "failure" }'
      - id: Notify_success
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() && contains(needs.*.result, 'success') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          job: '{ "status": "success" }'