name: Check notification

on:
  push: {}
  release: {}

jobs:
  failing:
    name: test failure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Try to fail
      run: exit 1
  if_failure:
    name: Only if failure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: Forced_failure
        name: Try to fail
        run: exit 1
      - id: Notify_failure
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          needs: ${{ env.needs }}
          job: ${{ toJson(job) }}
          steps: ${{ env.steps }}
