name: Check notification

on:
  push: {}
  release: {}

jobs:
  build:
    name: test failure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Try to fail
      run: exit 1
  notify:
    needs:
      - build
    name: sending message
    runs-on: ubuntu-latest
    if: always()
    steps:
      - id: Notify_failure
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          job: '{ "status": "failure" }'
      - id: Notify_success
        name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() && contains(needs.*.result, 'success') }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK}}
          job: '{ "status": "success" }'